name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest pytest-cov pytest-timeout
    
    - name: Run tests
      run: |
        pytest tests/test_simple.py -v --cov=. --cov-report=html --cov-fail-under=40 --timeout=30
    
    - name: Build Docker image
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          wikipedia-navigator:latest
          wikipedia-navigator:${{ github.ref_name }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## 🚀 Wikipedia Navigator ${{ github.ref_name }}
          
          ### ✨ Features
          - Enhanced Wikipedia navigation
          - REST API with web interface
          - Redis caching support
          - Docker containerization
          - Comprehensive testing
          
          ### 🔧 Technical Improvements
          - CI/CD pipeline with GitHub Actions
          - Security scanning with bandit and safety
          - Code quality checks with flake8
          - Test coverage reporting
          
          ### 📦 Docker Image
          ```
          docker pull wikipedia-navigator:${{ github.ref_name }}
          ```
          
          ### 🚀 Quick Start
          ```bash
          docker-compose up -d
          open http://localhost:8000
          ```
        draft: false
        prerelease: false
    
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: htmlcov/
        retention-days: 30
